enum DatasetType {
    STAR_PROPERTIES = 'STAR_PROPERTIES',
    PLANET_PROPERTIES = 'PLANET_PROPERTIES',
    TARGET_PIXEL = 'TARGET_PIXEL',
    SYSTEM_NAMES = 'SYSTEM_NAMES'
}

export default DatasetType