enum DatasetType {
    STAR_PROPERTIES = 'STAR_PROPERTIES',
    LIGHT_CURVE = 'LIGHT_CURVE',
    PLANET_PROPERTIES = 'PLANET_PROPERTIES',
    TARGET_PIXEL = 'TARGET_PIXEL',
    RADIAL_VELOCITY = 'RADIAL_VELOCITY'
}

export default DatasetType